### ISSUE TITLE
【依頼】最終課題挙動確認

### ISSUE THREAD

**Issue by yunakkano** [munerin2011/fleamarket_sample_73b#52]
■ URL
アドレス : https://www.furima73b.com/
Github（最終課題のリポジトリ）：https://github.com/munerin2011/fleamarket_sample_73b

■ Basic認証
ID：team_73_b
Pass：73_b_fleamarket

■ テスト用アカウント
◯ 購入者用
メールアドレス：test1@test.com
パスワード：0000000

◯ 購入用カード情報
番号：4242424242424242
期限：12/20
セキュリティカード：123

◯ 出品者用
メールアドレス：test2@test.com
パスワード：0000000

**Comment by divyumi** [comment]
73期Bチームさん
提出ありがとうございます！
商品出品時に複数枚投稿をすると以下の画像のように、二重に表示されてしまいます。
修正の上再度ご提出をお願いいたします。
<img width="260" alt="スクリーンショット 2020-09-04 17 30 08" src="https://user-images.githubusercontent.com/48047141/92218721-80d2d680-eed4-11ea-8448-15c4ead3db86.png">

**Comment by divyumi** [comment]
73期Bチームさん
先程の指摘ですが、改めて社内確認をとったところ修正不要とのことでした！
大変失礼致しました。
LGTMとさせていただきます！
また投稿したものの中に通信環境の問題か、詳細画面が表示出来ないものがございます。
こちらで削除が出来なかったので、お手数ですが削除をお願いいたします。(添付画像の商品
<img width="246" alt="スクリーンショット 2020-09-04 18 03 49" src="https://user-images.githubusercontent.com/48047141/92221844-0c4e6680-eed9-11ea-876f-674eff24b2c5.png">
）

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかチーム内で再度確認しましょう。**

**Comment by yunakkano** [comment]
動作確認ありがとうございました
